groups: []
resources:
- name: branch-watcher
  type: github-release
  source:
    owner: bradfordboyle
    pre_release: true
    repository: branch-watcher
resource_types: []
jobs:
- name: check-gp-continuous-integration
  plan:
  - get: branch-watcher
  - task: check-gp-continuous-integration
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: openjdk
          tag: 8-jdk-alpine
      run:
        path: sh
        args:
        - -exc
        - |
          java -jar branch-watcher/branch-watcher-0.1.0-SNAPSHOT-standalone.jar pivotal gp-continuous-integration
      inputs:
      - name: branch-watcher
    params:
      GITHUB_TOKEN: ((github_token))
